#!/bin/bash

# Convert environment variables in the conf to fixed entries
# http://stackoverflow.com/questions/21056450/how-to-inject-environment-variables-in-varnish-configuration
for name in VARNISH_BACKEND_PORT VARNISH_BACKEND_IP
do
    eval value=\$$name
    sed -i "s|\${${name}}|${value}|g" /etc/varnish/default.vcl
done

# Start varnish and log
varnishd -F -a 0.0.0.0:${VARNISH_PORT} -T 0.0.0.0:6082 -f /etc/varnish/default.vcl -s malloc,${VARNISH_MEMORY}
varnishlog
